{% set name = "rp2biosensor" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - networkx
    - rdkit
    - pytest
    - rr_cache

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - pytest -v

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: "Build Sensing-Enabling Metabolic Pathways from RetroPath2.0 output"
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tduigou
